const express = require('express');
const router = express.Router();

router.get('/',(req , res )=>{

    // Generating the 4 digit number
    var val = Math.floor(1000 + Math.random() * 9000);

    return res.status(200).json({
        message : `SMS GENERATED BY THE VI is ${val}`,
        provider : "VI",
        YourNumber : req.query.mobileNumber
    })
});

module.exports = router;